"$schema" = "https://starship.rs/config-schema.json"

# colorscheme
#
# #2E3440
# #3B4252
# #434C5E
# #4C566A
# #D8DEE9
# #E5E9F0
# #ECEFF4
# #8FBCBB
# #88C0D0
# #81A1C1
# #5E81AC
# #BF616A
# #D08770
# #EBCB8B
# #A3BE8C
# #B48EAD

# format = """
# $username\
# $directory\
# $git_branch\
# $git_status\
# $c\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $python\
# $rust\
# [\uE0B0 ](fg:#81A1C1 bg:#2E3440)\
# $line_break\
# $character
# """

format = "$direnv$directory$character"

# only works with certain shells
right_format = "$rust$c$golang$ruby$nodejs$python$git_status$git_branch"

# add_newline = false
command_timeout = 2000

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

# [colorscheme]
# black = "#2E3440"
# gray4 = "#3B4252"
# gray3 = "#434C5E"
# gray2 = "#4C566A"
# gray1 = "#D8DEE9"
# gray0 = "#E5E9F0"
# white = "#ECEFF4"
# color0 = "#8FBCBB"
# color1 = "#88C0D0"
# color2 = "#81A1C1"
# color3 = "#5E81AC"
# color4 = "#BF616A"
# color5 = "#D08770"
# color6 = "#EBCB8B"
# color7 = "#A3BE8C"
# color8 = "#B48EAD"

[character]
success_symbol = "[\u03BB](fg:#ECEFF4)"
error_symbol = "[\u03BB](fg:#BF616A)"

# system

[username]
show_always = true
style_user = "bg:#4C566A"
style_root = "bg:#4C566A"
format = "[    ]($style)[\uE0BC](bg:#BF616A fg:#4C566A)"

[directory]
style = "bold fg:#81A1C1"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

# git

[git_branch]
symbol = "\uE0A0"
format = "(fg:#ECEFF4) [$symbol $branch ](bold fg:#B48EAD)[\ueb04](bold fg:#A3BE8C)"

[git_metrics]
disabled = false

[git_status]
format = "[\ueb04](bold fg:#A3BE8C) [($all_status$ahead_behind)]($style)[\ueb04](bold fg:#A3BE8C)"
style = "bold fg:#D08770"
conflicted = "[\uebda](bold fg:#BF616A) $count "
ahead = "[\uF431](bold fg:#81A1C1) $count "
behind = "[\uF433](bold fg:#81A1C1) $count "
diverged = "[\uF418](bold fg:#EBCB8B) $count "
untracked = "[\uF4DC](bold fg:#EBCB8B) $count "
stashed = "[\uF4dd](bold fg:#ECEFF4) $count "
modified = "[\uF4D2](bold fg:#A3BE8C) $count "
staged = "[\uF4D0](bold fg:#A3BE8C) $count "
renamed = "[\uF4DC](bold fg:#BF616A) $count "
deleted = "[\uF48E](bold fg:#BF616A) $count "

[direnv]
symbol = "\uec10"
format = "[ $symbol](fg:#A3BE8C)"
disabled = false

# languages

[c]
symbol = "©"
style = "bg:#81A1C1 fg:#4C566A"
format = "[$symbol (${version})]($style) "

[elixir]
symbol = "\uE62D"
style = "bg:#81A1C1 fg:#4C566A"
format = "[$symbol (${version})]($style) "

[elm]
symbol = "\uE62C"
style = "bg:#81A1C1 fg:#4C566A"
format = "[$symbol (${version})]($style) "

[golang]
symbol = "\uE627"
style = "fg:#81A1C1"
format = "[$symbol (${version})]($style) "

[haskell]
symbol = "\uE777"
style = "bg:#EBCB8B"
format = "[$symbol (${version})]($style) "

[nodejs]
symbol = "\uE718"
style = "fg:#D08770"
format = "[$symbol (${version})]($style) "

[python]
symbol = "\uE235"
pyenv_version_name = true
style = "fg:#A3BE8C"
format = "[$symbol (${version}) ($virtualenv)]($style) "

[rust]
symbol = "\ue68b"
style = "fg:#BF616A"
format = "[$symbol (${version})]($style) "

[ruby]
symbol = "\uE23e"
style = "fg:#BF616A"
format = "[$symbol (${version})]($style) "
