"$schema" = "https://starship.rs/config-schema.json"

# colorscheme
#
# #2E3440
# #3B4252
# #434C5E
# #4C566A
# #D8DEE9
# #E5E9F0
# #ECEFF4
# #8FBCBB
# #88C0D0
# #81A1C1
# #5E81AC
# #BF616A
# #D08770
# #EBCB8B
# #A3BE8C
# #B48EAD

# format = """
# $username\
# $directory\
# $git_branch\
# $git_status\
# $c\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $python\
# $rust\
# [\uE0B0 ](fg:#81A1C1 bg:#2E3440)\
# $line_break\
# $character
# """

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character
"""

# only works with certain shells
right_format = "$time"

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

# [colorscheme]
# black = "#2E3440"
# gray4 = "#3B4252"
# gray3 = "#434C5E"
# gray2 = "#4C566A"
# gray1 = "#D8DEE9"
# gray0 = "#E5E9F0"
# white = "#ECEFF4"
# color0 = "#8FBCBB"
# color1 = "#88C0D0"
# color2 = "#81A1C1"
# color3 = "#5E81AC"
# color4 = "#BF616A"
# color5 = "#D08770"
# color6 = "#EBCB8B"
# color7 = "#A3BE8C"
# color8 = "#B48EAD"

# [character]
# success_symbol = "[ \uE007 ](bg:#4C566A)[\uE0BC](fg:#4C566A)"
# error_symbol = "[ \uE007 ](bg:#4C566A fg:#BF616A)[\uE0BC](fg:#4C566A)"

[character]
success_symbol = "[ \uE007](fg:#ECEFF4)"
error_symbol = "[ \uE007](fg:#ECEFF4)"

# system

[username]
show_always = true
style_user = "bg:#4C566A"
style_root = "bg:#4C566A"
# format = "[ $user ]($style)[\uE0BC](bg:#BF616A fg:#4C566A)"
format = "[    ]($style)[\uE0BC](bg:#BF616A fg:#4C566A)"
 
# [directory]
# style = "bg:#BF616A"
# format = "[ $path ]($style)[\uE0BE](bg:#BF616A fg:#D08770)"
# truncate_to_repo = false
# truncation_length = 3
# truncation_symbol = "…/"
 
[directory]
style = "bold fg:#81A1C1"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

# git

# [git_branch]
# symbol = "\uE0A0"
# style = "bg:#D08770"
# format = "[[ $symbol $branch ](bg:#D08770)]($style)"

[git_branch]
symbol = "\uE0A0"
format = "[on](fg:#ECEFF4) [$symbol $branch ](bold fg:#B48EAD)"
 
[git_metrics]
disabled = false

# [git_status]
# format = "[($all_status$ahead_behind)]($style)[\uE0BC](bg:#81A1C1 fg:#D08770)"
# style = "bg:#D08770"
# conflicted = "👿 $count "
# ahead = "⇡ $count "
# behind = "⇣ $count "
# diverged = " $count "
# untracked = "🤷‍ $count "
# stashed = "📦 $count "
# modified = "פֿ $count "
# staged = "+ $count "
# renamed = " $count "
# deleted = "🗑 $count "

[git_status]
format = "[\ueb10](bold fg:#A3BE8C) [($all_status$ahead_behind)]($style)[\ueb10](bold fg:#A3BE8C) "
style = "bold fg:#D08770"
conflicted = "[\uf4dc](bold fg:#BF616A) $count "
ahead = "[\uf431](bold fg:#81A1C1) $count "
behind = "[\uf433](bold fg:#81A1C1) $count "
diverged = "[\uf418](bold fg:#EBCB8B) $count "
untracked = "[\uf4d6](bold fg:#EBCB8B) $count "
stashed = "[\uf487](bold fg:#ECEFF4) $count "
modified = "[\uf4d2](bold fg:#A3BE8C) $count "
staged = "[\uf4d0](bold fg:#A3BE8C) $count "
renamed = "[\uf4d6](bold fg:#BF616A) $count "
deleted = "[\uf48e](bold fg:#BF616A) $count "

# languages

[c]
symbol = "© "
style = "bg:#81A1C1 fg:#4C566A"
format = "[ $symbol]($style)"
 
[elixir]
symbol = "\uE62D "
style = "bg:#81A1C1 fg:#4C566A"
format = "[ $symbol]($style)"
 
[elm]
symbol = "\uE62C "
style = "bg:#81A1C1 fg:#4C566A"
format = "[ $symbol]($style)"
 
[golang]
symbol = "\uE627 "
style = "bg:#81A1C1 fg:#4C566A"
format = "[ $symbol]($style)"
 
[haskell]
symbol = "\uE777 "
style = "bg:#81A1C1 fg:#4C566A"
format = "[ $symbol]($style)"
 
[nodejs]
symbol = "\uE718"
style = "fg:#81A1C1"
format = "/ [$symbol]($style) "
 
# [python]
# symbol = "\uE73C "
# pyenv_version_name = true
# style = "bg:#81A1C1 fg:#4C566A"
# format = "[ $symbol(${version} )]($style)"
 
[python]
symbol = "\uE73C"
pyenv_version_name = true
style = "fg:#A3BE8C"
# style = "bold fg:#A3BE8C"
format = "/ [$symbol]($style) "
 
[rust]
symbol = "\uE7A8 "
style = "bg:#81A1C1 fg:#4C566A"
format = "[ $symbol]($style)"
 
[ruby]
symbol = "\uE739"
style = "fg:#BF616A"
format = "/ [$symbol]($style) "
